// <auto-generated />
using System;
using G2rismBeta.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G2rismBeta.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205002642_CompletarModuloVuelos")]
    partial class CompletarModuloVuelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("G2rismBeta.API.Models.Aerolinea", b =>
                {
                    b.Property<int>("IdAerolinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aerolinea");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAerolinea"));

                    b.Property<string>("CodigoIata")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("codigo_iata");

                    b.Property<string>("CodigoIcao")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("codigo_icao");

                    b.Property<string>("EmailContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email_contacto");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pais");

                    b.Property<string>("PoliticasEquipaje")
                        .HasColumnType("TEXT")
                        .HasColumnName("politicas_equipaje");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sitio_web");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono_contacto");

                    b.HasKey("IdAerolinea");

                    b.HasIndex("CodigoIata")
                        .IsUnique()
                        .HasDatabaseName("IX_Aerolineas_CodigoIata");

                    b.HasIndex("CodigoIcao")
                        .IsUnique()
                        .HasDatabaseName("IX_Aerolineas_CodigoIcao");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Aerolineas_Estado");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Aerolineas_Nombre");

                    b.HasIndex("Pais")
                        .HasDatabaseName("IX_Aerolineas_Pais");

                    b.ToTable("aerolineas");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.CategoriaCliente", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Beneficios")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("beneficios");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_hex");

                    b.Property<string>("CriteriosClasificacion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("criterios_clasificacion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("descuento_porcentaje");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.HasIndex("DescuentoPorcentaje")
                        .HasDatabaseName("idx_categoria_cliente_descuento");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_categoria_cliente_estado");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_categoria_cliente_nombre_unique");

                    b.ToTable("categorias_cliente");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("documento_identidad");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pais");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("IdCliente");

                    b.HasIndex("Ciudad")
                        .HasDatabaseName("idx_cliente_ciudad");

                    b.HasIndex("CorreoElectronico")
                        .HasDatabaseName("idx_cliente_email");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique()
                        .HasDatabaseName("idx_cliente_documento_unique");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_cliente_estado");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("idx_cliente_categoria");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Apellido", "Nombre")
                        .HasDatabaseName("idx_cliente_apellido_nombre");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.CodigoRecuperacion", b =>
                {
                    b.Property<int>("IdCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_codigo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCodigo"));

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bloqueado");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_generacion");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_uso");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IntentosValidacion")
                        .HasColumnType("int")
                        .HasColumnName("intentos_validacion");

                    b.Property<string>("IpSolicitud")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_solicitud");

                    b.Property<string>("TipoCodigo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_codigo");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("usado");

                    b.HasKey("IdCodigo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("idx_codigo_unique");

                    b.HasIndex("FechaExpiracion")
                        .HasDatabaseName("idx_codigo_expiracion");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_codigo_usuario");

                    b.HasIndex("IdUsuario", "Usado", "Bloqueado", "FechaExpiracion")
                        .HasDatabaseName("idx_codigo_usuario_activo");

                    b.ToTable("codigos_recuperacion");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.ContratoProveedor", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<string>("ArchivoContrato")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("archivo_contrato");

                    b.Property<string>("CondicionesPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condiciones_pago");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_contrato");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<bool>("RenovacionAutomatica")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("renovacion_automatica");

                    b.Property<string>("Terminos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("terminos");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_contrato");

                    b.Property<decimal>("ValorContrato")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_contrato");

                    b.HasKey("IdContrato");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_contrato_estado");

                    b.HasIndex("FechaFin")
                        .HasDatabaseName("idx_contrato_fecha_fin");

                    b.HasIndex("IdProveedor")
                        .HasDatabaseName("idx_contrato_proveedor");

                    b.HasIndex("NumeroContrato")
                        .IsUnique()
                        .HasDatabaseName("idx_contrato_numero_unique");

                    b.HasIndex("Estado", "FechaFin")
                        .HasDatabaseName("idx_contrato_estado_fecha_fin");

                    b.ToTable("contratos_proveedor");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_identidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int?>("IdJefe")
                        .HasColumnType("int")
                        .HasColumnName("id_jefe");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Salario")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("salario");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("Cargo")
                        .HasDatabaseName("idx_empleado_cargo");

                    b.HasIndex("CorreoElectronico")
                        .HasDatabaseName("idx_empleado_email");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique()
                        .HasDatabaseName("idx_empleado_documento_unique");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_empleado_estado");

                    b.HasIndex("IdJefe")
                        .HasDatabaseName("idx_empleado_jefe");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Apellido", "Nombre")
                        .HasDatabaseName("idx_empleado_apellido_nombre");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modulo");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_permiso");

                    b.HasKey("IdPermiso");

                    b.HasIndex("NombrePermiso")
                        .IsUnique()
                        .HasDatabaseName("idx_permiso_nombre_unique");

                    b.HasIndex("Modulo", "Accion")
                        .HasDatabaseName("idx_permiso_modulo_accion");

                    b.ToTable("permisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.PreferenciaCliente", b =>
                {
                    b.Property<int>("IdPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_preferencia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPreferencia"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Intereses")
                        .HasColumnType("json")
                        .HasColumnName("intereses");

                    b.Property<string>("PreferenciasAlimentacion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("preferencias_alimentacion");

                    b.Property<decimal?>("PresupuestoPromedio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("presupuesto_promedio");

                    b.Property<string>("TipoAlojamiento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_alojamiento");

                    b.Property<string>("TipoDestino")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_destino");

                    b.HasKey("IdPreferencia");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasDatabaseName("idx_preferencia_cliente");

                    b.ToTable("preferencias_cliente");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<decimal>("Calificacion")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("calificacion");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CorreoAlternativo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo_alternativo");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NitRut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nit_rut");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_contacto");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_empresa");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pais");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sitio_web");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TelefonoAlternativo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono_alternativo");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_proveedor");

                    b.HasKey("IdProveedor");

                    b.HasIndex("Calificacion")
                        .HasDatabaseName("idx_proveedor_calificacion");

                    b.HasIndex("Ciudad")
                        .HasDatabaseName("idx_proveedor_ciudad");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_proveedor_estado");

                    b.HasIndex("NitRut")
                        .IsUnique()
                        .HasDatabaseName("idx_proveedor_nit_unique");

                    b.HasIndex("NombreEmpresa")
                        .HasDatabaseName("idx_proveedor_nombre");

                    b.HasIndex("TipoProveedor")
                        .HasDatabaseName("idx_proveedor_tipo");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("IdRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_refresh_token");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRefreshToken"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_revocacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_creacion");

                    b.Property<string>("ReemplazadoPor")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("reemplazado_por");

                    b.Property<bool>("Revocado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revocado");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("IdRefreshToken");

                    b.HasIndex("FechaExpiracion")
                        .HasDatabaseName("idx_refresh_token_expiracion");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_refresh_token_usuario");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_token_unique");

                    b.HasIndex("IdUsuario", "Revocado", "FechaExpiracion")
                        .HasDatabaseName("idx_refresh_token_usuario_activo");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("NivelAcceso")
                        .HasColumnType("int")
                        .HasColumnName("nivel_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("NivelAcceso")
                        .HasDatabaseName("idx_rol_nivel_acceso");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_rol_nombre_unique");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion");

                    b.HasKey("IdRol", "IdPermiso")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("IdPermiso");

                    b.ToTable("roles_permisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.TokenRecuperacion", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_token");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdToken"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_generacion");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_uso");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpSolicitud")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_solicitud");

                    b.Property<string>("TipoToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("usado");

                    b.HasKey("IdToken");

                    b.HasIndex("FechaExpiracion")
                        .HasDatabaseName("idx_token_expiracion");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_token_usuario");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_token_unique");

                    b.ToTable("tokens_recuperacion");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bloqueado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int")
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo_usuario");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_email_unique");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_usuario_estado");

                    b.HasIndex("TipoUsuario")
                        .HasDatabaseName("idx_usuario_tipo");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_username_unique");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int?>("AsignadoPor")
                        .HasColumnType("int")
                        .HasColumnName("asignado_por");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("IdRol")
                        .HasDatabaseName("idx_usuario_rol_rol");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_usuario_rol_usuario");

                    b.ToTable("usuarios_roles");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Vuelo", b =>
                {
                    b.Property<int>("IdVuelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vuelo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVuelo"));

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("int")
                        .HasColumnName("cupos_disponibles");

                    b.Property<int>("CuposTotales")
                        .HasColumnType("int")
                        .HasColumnName("cupos_totales");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destino");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duracion_minutos");

                    b.Property<int>("Escalas")
                        .HasColumnType("int")
                        .HasColumnName("escalas");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaLlegada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_llegada");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_salida");

                    b.Property<TimeSpan>("HoraLlegada")
                        .HasColumnType("time(6)")
                        .HasColumnName("hora_llegada");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time(6)")
                        .HasColumnName("hora_salida");

                    b.Property<int>("IdAerolinea")
                        .HasColumnType("int")
                        .HasColumnName("id_aerolinea");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_vuelo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origen");

                    b.Property<decimal>("PrecioEconomica")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_economica");

                    b.Property<decimal?>("PrecioEjecutiva")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_ejecutiva");

                    b.HasKey("IdVuelo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_vuelo_estado");

                    b.HasIndex("FechaSalida")
                        .HasDatabaseName("idx_vuelo_fecha_salida");

                    b.HasIndex("IdAerolinea")
                        .HasDatabaseName("idx_vuelo_aerolinea");

                    b.HasIndex("IdProveedor")
                        .HasDatabaseName("idx_vuelo_proveedor");

                    b.HasIndex("NumeroVuelo")
                        .IsUnique()
                        .HasDatabaseName("idx_vuelo_numero_unique");

                    b.HasIndex("Origen", "Destino")
                        .HasDatabaseName("idx_vuelo_origen_destino");

                    b.ToTable("vuelos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Cliente", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.CategoriaCliente", "Categoria")
                        .WithMany("Clientes")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cliente_categoria");

                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_usuario");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.CodigoRecuperacion", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany("CodigosRecuperacion")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_codigo_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.ContratoProveedor", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Proveedor", "Proveedor")
                        .WithMany("Contratos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contrato_proveedor");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Empleado", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Empleado", "Jefe")
                        .WithMany("Subordinados")
                        .HasForeignKey("IdJefe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_empleado_jefe");

                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empleado_usuario");

                    b.Navigation("Jefe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.PreferenciaCliente", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Cliente", "Cliente")
                        .WithOne("Preferencia")
                        .HasForeignKey("G2rismBeta.API.Models.PreferenciaCliente", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preferencia_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.RefreshToken", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.RolPermiso", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_permiso_permiso");

                    b.HasOne("G2rismBeta.API.Models.Rol", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_permiso_rol");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.TokenRecuperacion", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany("TokensRecuperacion")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.UsuarioRol", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_rol");

                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Vuelo", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Aerolinea", "Aerolinea")
                        .WithMany("Vuelos")
                        .HasForeignKey("IdAerolinea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G2rismBeta.API.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vuelo_proveedor");

                    b.Navigation("Aerolinea");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Aerolinea", b =>
                {
                    b.Navigation("Vuelos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.CategoriaCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Cliente", b =>
                {
                    b.Navigation("Preferencia");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Empleado", b =>
                {
                    b.Navigation("Subordinados");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Proveedor", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Rol", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Usuario", b =>
                {
                    b.Navigation("CodigosRecuperacion");

                    b.Navigation("TokensRecuperacion");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
